server {
    listen 80;

    location /search {
        proxy_pass http://pattern-search-backend:8000;
        proxy_set_header Host $host;
    }

    location /parse {
        proxy_pass http://pattern-search-backend:8000;
        proxy_set_header Host $host;
    }

    location /movies {
        proxy_pass http://pattern-search-backend:8000;
        proxy_set_header Host $host;
    }

    location /cards {
        proxy_pass http://pattern-search-backend:8000;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
